### ISSUE TITLE
BpkButton seems to be a bit too narrow

### ISSUE THREAD

**Issue by Szabadember** [Skyscanner/backpack-android#200]
Buttons height seems to be a bit too small compared to iOS.

![screenshot_20190225-051843](https://user-images.githubusercontent.com/5400248/53332085-bf0c3480-38f2-11e9-87ac-f3dc452faa60.jpg)

**Comment by olliecurtis** [comment]
Hello 👋 Closing this issue as we have since undergone a brand refresh and this component has been updated. Hopefully the new design fits the needs and is improved?

Feel free to re-open if you feel there is still room for improvement 😄 

Thanks
