### ISSUE TITLE
Cannot install the HockeyApp apk in the emulator

### ISSUE THREAD

**Issue by siempredelao** [Skyscanner/backpack-android#254]
Hey folks! I'm trying to install the apk available in HockeyApp (Version 7.5.0 (1), 06 May 2019, 12:52) in my emulator but it is throwing the following error:

![image](https://user-images.githubusercontent.com/5559829/57684141-7e8c9f00-7635-11e9-9a45-2eb36099076d.png)

I tried a couple of months ago and it didn't work either. Do you have any idea what might I be doing wrong?

Thanks and great job btw!!! :clap:

**Comment by tiagoengel** [comment]
Hi @siempredelao, thanks for raising this. Seems like we have a problem with the signature of the app we are publishing in HockeyApp. 

I'll try to have a look at it when I have some free time. If you want to run it locally in the meantime it should be very straightforward to clone and run it :).

**Comment by truistic** [comment]
Cannot install the demo application in my phone. INSTALL_PARSE_FAILED_NO_CERTIFICATES

**Comment by bvitaliyg** [comment]
This should be fixed now with https://github.com/Skyscanner/backpack-android/pull/386
