### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by ataulm** [Skyscanner/backpack-android#600]
I'm trying to import Backpack into my project and I'm getting resource linking errors. I'm using version 29.0.0 because at the time of writing, the newer ones aren't building successfully on Jitpack.

```
/Users/amunim/.gradle/caches/transforms-3/13cf8cefe233e09aab453a1214846e51/transformed/jetified-backpack-android-29.0.0/res/values/values.xml: AAPT: error: resource font/skyscanner_relative_android_book (aka com.example:font/skyscanner_relative_android_book) not found.
    
/Users/amunim/.gradle/caches/transforms-3/13cf8cefe233e09aab453a1214846e51/transformed/jetified-backpack-android-29.0.0/res/values/values.xml: AAPT: error: resource font/skyscanner_relative_android_bold (aka com.example:font/skyscanner_relative_android_bold) not found.
    
/Users/amunim/.gradle/caches/transforms-3/13cf8cefe233e09aab453a1214846e51/transformed/jetified-backpack-android-29.0.0/res/values/values.xml: AAPT: error: resource font/skyscanner_relative_android_black (aka com.example:font/skyscanner_relative_android_black) not found.
```

If I add some arbitrary fonts (with those names) in my `res/font` directory, I get past that error and onto another issue:

```
AAPT: error: resource style/BpkTheme (aka com.example:style/BpkTheme) not found.
error: failed linking references.
```

Instead of using `BpkTheme`, I can use `BpkDefaultTheme` with no issue (is the README outdated?), but it's also necessary not to use `AppCompatActivity`, nor any Material widgets like `MaterialButton`. Then it builds and runs.

---

I'm unsure if that's the _correct_ approach though, and whether I'm missing things because of these workarounds.

**Comment by marianeum** [comment]
Thanks for the report! We have now published a new version 31.0.0 which should fix these issues. 

Regards the missing `BpkTheme` this should also be solved by using version 31.0.0 - the theme was introduced after version 29.0.0, so the `README` was referring to the latest version.
